jobs:
  build:
    docker:
      - image: eclipse/ubuntu_jdk8
      - image: eclipse/cpp_gcc
    steps:
      - checkout
      - run:
          name: Building
          command: g++ -o hello -c hello.cpp
      - run:
          name: List the output
          command: ls
          
