jobs:
  build:
    machine: true
      image: circleci/classic:latest
    docker:
      - image: anitagov/ubuntu-gcc
    steps:
      - checkout
      - run: | 
          g++ -o hello hello.cpp &&
          ./hello
          
