jobs:
  build:
    docker:
      - image: eclipse/cpp_gcc
    steps:
      - checkout
      - run:
          name: Building
          command: g++ -o hello hello.cpp
      - run:
          name: Run the App
          command: ./hello
          
