jobs:
  build:
    docker: 
      - image: anitagov/ubuntu-tools:1.2
    steps:
      - checkout
      - run: | 
          export SHELL=/bin/bash &&
          export shell=/bin/bash &&
          sudo make -C drivers &&
          find drivers -name isgx.ko -print
