jobs:
  build:
    docker:
      - image: ubuntu:14:04
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, CircleCI.
      - run:
          name: Print the Current Time
          command: date