jobs:
  build:
    docker: 
      - image: anitagov/ubuntu-tools:1.1
    steps:
      - checkout
      - run: | 
          export SHELL=/bin/bash &&
          export shell=/bin/bash &&
          apt-get -y update &&
          apt-get -y install sudo &&
          apt-get -y install linux-generic
          apt-get -y install kmod
          sudo make -C drivers
