jobs:
  build:
    docker:
      - image: eclipse/ubuntu_jdk8
    steps:
      - checkout
      - run:
          name: Installing gcc
          command: sudo apt-get install gcc
      - run:
          name: Building
          command: gcc -o hello -c hello.cpp
      - run:
          name: List the output
          command: ls
          
