jobs:
  build:
    docker: 
      - image: anitagov/ubuntu-tools:1.1
    steps:
      - checkout
      - git clone https://github.com/intel/linux-sgx.git
      - run: |
          cmake . &&
          make &&
          ./Fantastic 120
          
