jobs:
  build:
      machine: 
      enabled: true
      image: circleci/classic:latest
    steps:
      - checkout
      - run: | 
          sudo ./scripts/install.tools &&
          export SHELL=/bin/bash &&
          export shell=/bin/bash &&
          sudo make -C drivers &&
          find drivers -name isgx.ko -print
