jobs:
  build:
    docker: 
      - image: anitagov/ubuntu-tools:1.1
    steps:
      - checkout
      - run: | 
          export SHELL=/bin/bash &&
          apt-get -y update &&
          apt-get -y install sudo &&
          sudo make -C drivers &&
          sudo make -C drivers install
