jobs:
  build:
    docker:
      - image: eclipse/ubuntu_jdk8
      - image: eclipse/cpp_gcc
    steps:
      - checkout
      - run:
          name: CPPGreeting
          command: g++ -o hello -c hello.cpp
          command: ./hello 
      - run:
          name: Print the Current Time
          command: date
