#!/bin/bash

# Install required packages.
#
#
apt-get -y install update
apt-get -y install clang-format
apt-get -y install cmake

apt-get -y install doxygen

apt-get -y install gawk
apt-get -y install gcc
apt-get -y install g++

apt-get -y install libexpat1-dev
apt-get -y install libssl-dev
apt-get -y install make

apt-get -y install openssl
apt-get -y install subversion
